!!python/object:utils.misc.Args
activation: !!python/name:torch.nn.modules.activation.SiLU ''
augmentations:
  crop:
  - 0.64
  - 1.0
  hflip: 0
  mask:
  - 0.0
  - 0.25
  - 8
  - 16
  perspective: 0.0
batch_size: 384
check_frequency: 480
class_names:
- aircraft carrier
- airplane
- alarm clock
- ambulance
- angel
- animal migration
- ant
- anvil
- apple
- arm
- asparagus
- axe
- backpack
- banana
- bandage
- barn
- baseball
- baseball bat
- basket
- basketball
- bat
- bathtub
- beach
- bear
- beard
- bed
- bee
- belt
- bench
- bicycle
- binoculars
- bird
- birthday cake
- blackberry
- blueberry
- book
- boomerang
- bottlecap
- bowtie
- bracelet
- brain
- bread
- bridge
- broccoli
- broom
- bucket
- bulldozer
- bus
- bush
- butterfly
- cactus
- cake
- calculator
- calendar
- camel
- camera
- camouflage
- campfire
- candle
- cannon
- canoe
- car
- carrot
- castle
- cat
- ceiling fan
- cell phone
- cello
- chair
- chandelier
- church
- circle
- clarinet
- clock
- cloud
- coffee cup
- compass
- computer
- cookie
- cooler
- couch
- cow
- crab
- crayon
- crocodile
- crown
- cruise ship
- cup
- diamond
- dishwasher
- diving board
- dog
- dolphin
- donut
- door
- dragon
- dresser
- drill
- drums
- duck
- dumbbell
- ear
- elbow
- elephant
- envelope
- eraser
- eye
- eyeglasses
- face
- fan
- feather
- fence
- finger
- fire hydrant
- fireplace
- firetruck
- fish
- flamingo
- flashlight
- flip flops
- floor lamp
- flower
- flying saucer
- foot
- fork
- frog
- frying pan
- garden
- garden hose
- giraffe
- goatee
- golf club
- grapes
- grass
- guitar
- hamburger
- hammer
- hand
- harp
- hat
- headphones
- hedgehog
- helicopter
- helmet
- hexagon
- hockey puck
- hockey stick
- horse
- hospital
- hot air balloon
- hot dog
- hot tub
- hourglass
- house
- house plant
- hurricane
- ice cream
- jacket
- jail
- kangaroo
- key
- keyboard
- knee
- knife
- ladder
- lantern
- laptop
- leaf
- leg
- light bulb
- lighter
- lighthouse
- lightning
- line
- lion
- lipstick
- lobster
- lollipop
- mailbox
- map
- marker
- matches
- megaphone
- mermaid
- microphone
- microwave
- monkey
- moon
- mosquito
- motorbike
- mountain
- mouse
- moustache
- mouth
- mug
- mushroom
- nail
- necklace
- nose
- ocean
- octagon
- octopus
- onion
- oven
- owl
- paint can
- paintbrush
- palm tree
- panda
- pants
- paper clip
- parachute
- parrot
- passport
- peanut
- pear
- peas
- pencil
- penguin
- piano
- pickup truck
- picture frame
- pig
- pillow
- pineapple
- pizza
- pliers
- police car
- pond
- pool
- popsicle
- postcard
- potato
- power outlet
- purse
- rabbit
- raccoon
- radio
- rain
- rainbow
- rake
- remote control
- rhinoceros
- rifle
- river
- roller coaster
- rollerskates
- sailboat
- sandwich
- saw
- saxophone
- school bus
- scissors
- scorpion
- screwdriver
- sea turtle
- see saw
- shark
- sheep
- shoe
- shorts
- shovel
- sink
- skateboard
- skull
- skyscraper
- sleeping bag
- smiley face
- snail
- snake
- snorkel
- snowflake
- snowman
- soccer ball
- sock
- speedboat
- spider
- spoon
- spreadsheet
- square
- squiggle
- squirrel
- stairs
- star
- steak
- stereo
- stethoscope
- stitches
- stop sign
- stove
- strawberry
- streetlight
- string bean
- submarine
- suitcase
- sun
- swan
- sweater
- swing set
- sword
- syringe
- t-shirt
- table
- teapot
- teddy-bear
- telephone
- television
- tennis racquet
- tent
- the eiffel tower
- the great wall of china
- the mona lisa
- tiger
- toaster
- toe
- toilet
- tooth
- toothbrush
- toothpaste
- tornado
- tractor
- traffic light
- train
- tree
- triangle
- trombone
- truck
- trumpet
- umbrella
- underwear
- van
- vase
- violin
- washing machine
- watermelon
- waterslide
- whale
- wheel
- windmill
- wine bottle
- wine glass
- wristwatch
- yoga
- zebra
- zigzag
clip_name: ViT-B/16
datasets:
- DomainNet
device: cuda
drop_rate_psi_n_beta: 0
drop_rate_theta: 0
early_stop:
  delta: 0.01
  patience: 5
eval_sets:
  DomainNet:
  - clipart
  - infograph
  - painting
  - quickdraw
  - real
  - sketch
images_path: null
latent_dim: 512
learning_rate: 0.0001
load_weights: null
log_frequency: 50
manual_seed: 2024
noise_len: 0
optimizer: !!python/name:torch.optim.adam.Adam ''
out_dim: 512
prompt_aug_params:
  art_style: 0
  eda: false
  img_type: 0
  object_color: 0.5
  object_size: 0.5
  replace: false
  reverse: 0.5
prompts_path: data/prompts_template/DomainNet
repeat: 0
scale: 1
scale_coef: 0.0001
shuffle: true
std: 0.02
tau_cm: 0.5
tau_cnt: 1
tau_img: 0.5
tau_txt: 0.3
total_steps: 8000
weight_decay: 0
weights_path: null
which_network:
- beta
